### PR TITLE
Revamp UI Twitter Helper Section Page

### PR DESCRIPTION
**Pull request by Rarj**
### Revamp Twitter Helper

https://user-images.githubusercontent.com/23600466/136670725-e67e4906-ac47-4663-a085-ce76f2d54924.mp4

Feel free to comment if you wanna make a changes 😃

### CODE REVIEW

**Comment by Rarj** [comment]
Hi @sitamadex11 , please check my work. If you like it please accept this PR.
Thanks! 🔥

**Review by HeySitam — APPROVED** [review]
Great work. and very very sorry for the delay.

**Comment by Rarj** [comment]
No worries. 
But, my PR not counting on my hacktoberfest profile. Why its happened, btw?

**Comment by HeySitam** [comment]
I think some times it take some time. Please check it once again. And is
same happening with your previous PR?

**Comment by Rarj** [comment]
No. Its not happening with my previous PR. Its counting immediately when you accept my PR. 
I will try it again later to refresh my profile. Thanks anw😁

**Comment by HeySitam** [comment]
Ok then please let me know.

**Comment by Rarj** [comment]
Hi @sitamadex11 , this PR was counting on my profile. 
I will work with another task tonight. 

Thanks!

**Pull request merged**
