### PR TITLE
AddVolunteerFragment opens when Add Volunteer is clicked in the menu

### LINKED ISSUE #86: Clicking on Add Yourself as Volunteer doesnt take to proper Activity/fragment
https://user-images.githubusercontent.com/75211982/136657517-d2f9ca0f-611c-4ec8-b295-2a2912134347.mp4

### PR DESCRIPTION
**Pull request by anamansari062**
fixes #86

### CODE REVIEW

**Comment by HeySitam** [comment]
hey, can you please send a screen recording?

**Comment by anamansari062** [comment]
@sitamadex11 Sure

https://user-images.githubusercontent.com/85510030/138119400-b0beb67d-af67-4b64-a02d-3224359c02f3.mov

.

**Comment by HeySitam** [comment]
When you are clicking on `Add Yourself as Volunteer` then I think you are redirecting the user to the `AddVolunteer` fragment. But you are not checking else the user is already a volunteer or not.

**Comment by anamansari062** [comment]
Yes i can do that.

**Comment by HeySitam** [comment]
You can check the logic of the floating action button then implement the same accordingly.

**Comment by HeySitam** [comment]
> Yes i can do that.

sure go for it.

**Comment by anamansari062** [comment]
> You can check the logic of the floating action button then implement the same accordingly.

Yess

**Comment by anamansari062** [comment]
https://user-images.githubusercontent.com/85510030/139262574-6d369c8e-dd58-4bb3-b398-a2830bf6c60e.mov

**Comment by anamansari062** [comment]
@sitamadex11 I have completed the requested changes, please check

**Review by cdhiraj40 — APPROVED** [review]

**Comment by cdhiraj40** [comment]
@anamansari062 the approach looks good to me :)

**Review by HeySitam — APPROVED** [review]
Thank you for your PR.

**Pull request merged**
