### PR TITLE
Updated vaccine status UI

### PR DESCRIPTION
**Pull request by pratik9315**
WhatsApp Image 2021-10-07 at 12 23 08

I have made some changes,

First, the age textview was not being shown correctly in some of my phones so i moved to above where it had better space
Second, I adjusted some spacing within the card 
Overall i feel everything else was okay but let me know if you want me to revert any changes or make improvments in the existing ones. Thanks.

### CODE REVIEW

**Comment by pratik9315** [comment]
Extremely sorry about the merge conflicts i dont know whats going wrong. Can you guide me?

**Comment by PranavVyas20** [comment]
> Extremely sorry about the merge conflicts i dont know whats going wrong. Can you guide me?

You dont have to push the .idea files

**Comment by HeySitam** [comment]
@pratik2315 Have you fetched upstream?

**Comment by HeySitam** [comment]
May you please change the color combination to look more attractive?

**Comment by HeySitam** [comment]
@pratik2315 add the  `.idea` folder to `.gitignore` file. Then push it to your remote repository.

**Comment by pratik9315** [comment]
WhatsApp Image 2021-10-07 at 18 45 08
So.. I have tried this color combination, Ive tried to match it with the outer screen UI. can you take a look at it?
Thanks.

**Comment by pratik9315** [comment]
Yes @sitamadex11 I fetched upstream and also resolved the conflict regarding the .idea file as you instructed

**Comment by HeySitam** [comment]
Thankyou Verymuch. Looks Great.

**Review by HeySitam — APPROVED** [review]
Great work. Thanks for your PR.

**Comment by pratik9315** [comment]
Thanks for the support @sitamadex11 and @PranavVyas20🙏😃

**Comment by HeySitam** [comment]
😇

**Pull request merged**
