### PR TITLE
Updated Icon Set for the city and refactoring 

### PR DESCRIPTION
**Pull request by Zaraki596**
- **Updated icon set with the proper city name and indication**
- **Refactored the XML with proper style changes for future optimizations**

### CODE REVIEW

**Comment by HeySitam** [comment]
Bro, have you fetched the upstream?

**Comment by HeySitam** [comment]
Please resolve the conflicts.

**Comment by Zaraki596** [comment]
@sitamadex11 Bro updated the upstream but you have to do 
`git rm -r --cached .idea`
To remove the unwanted idea folder it is creating so many conflicts.
This need to be done from your side..so that configuration files of every one's IDE don't merge with the codebase

**Comment by HeySitam** [comment]
wait I am looking into it

**Comment by HeySitam** [comment]
Thankyou for your pr

**Comment by cdhiraj40** [comment]
> @sitamadex11 Bro updated the upstream but you have to do `git rm -r --cached .idea` To remove the unwanted idea folder it is creating so many conflicts. This need to be done from your side..so that configuration files of every one's IDE don't merge with the codebase

is this done, its always creating conflicts? Thanks, @Zaraki596 for mentioning it :)

**Comment by Zaraki596** [comment]
For me yes..when merging upstream branches..coz you don't know how many ide and pull request we have..

**Comment by HeySitam** [comment]
actually when I was testing then no conflicts were found. Then I delete the `develop` branch's `misc.xml` file where there were the conflict shows.

**Comment by HeySitam** [comment]
Then I have merged your PR.

**Pull request merged**
